"""Fixed-path shims for `bin/sync` and `bin/adopt`.

A GitHub-installed plugin root is `~/.config/herdr/plugins/github/<id>-<hash>/<subdir>`
and a linked one is wherever the user's checkout lives, so nothing outside the plugin can
name `bin/sync` without first digging the path out of `herdr plugin list --json`. Both
entrypoints are meant to be run by hand -- `--doctor` is the answer to "it did nothing and
I do not know why", and `adopt` is the whole inbound direction -- so that lookup stands
between the user and the two commands they need most.

The state directory is fixed at `~/.local/state/herdr/plugins/vscode-workspace-sync`, so
every Herdr-invoked run refreshes an executable shim there for each entrypoint. That gives
the README literal paths to hand out, and they keep working after a reinstall moves the
plugin root.

Refreshed from the hooks rather than from a daemon, because this plugin has none. The
common case is a single read: twelve event hooks fire this, and a shim whose content is
already right is left alone.
"""

import os
import shlex

ENV_STATE_DIR = "HERDR_PLUGIN_STATE_DIR"

PLUGIN_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ENTRYPOINTS = ("sync", "adopt")

LAUNCHER_HEADER = (
    "# Generated by vscode-workspace-sync. Do not edit -- rewritten on every hook run,\n"
    "# so it follows the plugin when a reinstall moves its directory.\n"
)


def write_launcher(path, entrypoint):
    """Refresh the executable shim at *path* so it execs `entrypoint "$@"`.

    Rewrites only when the content or the executable bit is wrong. Never raises: a
    convenience shim must not be able to fail a sync.
    """
    body = "#!/bin/sh\n%sexec %s \"$@\"\n" % (LAUNCHER_HEADER, shlex.quote(entrypoint))
    try:
        with open(path) as fh:
            if fh.read() == body and os.access(path, os.X_OK):
                return path
    except (IOError, OSError):
        pass

    tmp = "%s.tmp.%d" % (path, os.getpid())
    try:
        with open(tmp, "w") as fh:
            fh.write(body)
        os.chmod(tmp, 0o755)
        os.replace(tmp, path)
    except (IOError, OSError):
        try:
            os.unlink(tmp)
        except OSError:
            pass
    return path


def paths(env=None):
    """Where the shims live, or `{}` outside a Herdr-invoked run.

    Keyed strictly on `$HERDR_PLUGIN_STATE_DIR`: Herdr creates that directory at install
    or link time and injects it into every hook, so its absence means nobody has asked
    for these shims -- and a run from a test or a checkout must not scribble into the
    real state directory to find that out.
    """
    state_dir = (env or os.environ).get(ENV_STATE_DIR)
    if not state_dir:
        return {}
    return dict((name, os.path.join(state_dir, name)) for name in ENTRYPOINTS)


def refresh(env=None):
    """Rewrite any shim that is missing, stale or no longer executable."""
    found = paths(env)
    for name, path in found.items():
        write_launcher(path, os.path.join(PLUGIN_ROOT, "bin", name))
    return found
